language: python
python:
  - 3.6
install:
  - pip install coveralls
  - pip install -r requirements/development.txt
script:
  - python setup.py test
after_success:
  - coveralls
  - chmod 600 deploy-key
  - mv deploy-key ~/.ssh/id_rsa
  - git remote add deploy ssh://$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
  - git push deploy
before_install:
  - echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - openssl aes-256-cbc -K $encrypted_dd30eeb0a0a0_key -iv $encrypted_dd30eeb0a0a0_iv
    -in sandbox/certificates/id_rsa_fe_travis.enc -out deploy-key -d
