version: '3'

services:

  mysql:
    image: mysql:5.7.21
    volumes:
      - pessoa-mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    networks:
      - pessoa
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fe-pessoa

  web:
    build: .
    volumes:
      - ./requirements.txt:/requirements.txt
      - ./src:/app
    links:
      - mysql:mysql
    ports:
      - "9000:8000"
    networks:
      - ortopedica
    environment:
       DATABASE_URL: mysql://root:password@mysql:3306/fe-conta
    depends_on:
      - mysql

volumes:
  ortopedica-mysql:
  ortopedica-python:

networks:
  pessoa:


#fe_auth:
#  image: fernandoe/fe-auth-server:release_0.1.0
#  environment:
#   - DJANGO_SETTINGS_MODULE=server.settings.docker
#  volumes:
#    - ~/.docker-volumes/fe_auth/database:/database
#  ports:
#    - 7000:8000
#
#fe_pessoa:
#  dockerfile: Dockerfile
#  build: .
#  environment:
#   - DJANGO_SETTINGS_MODULE=server.settings.docker
#  links:
#    - fe_auth
#  volumes:
#    - ./requirements:/requirements
#    - ./source:/app
#    - ~/.docker-volumes/fe_auth/database:/database
#  ports:
#    - 7001:8000
