# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fe_pessoa', '0002_auto_20170616_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='entidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fe_core.Entity'),
        ),
    ]
